const products = [
    {
        images: 'images/carrosel1.jpg',
        title: 'Tradicional',
        desc: 'Bem casado tradicional(doce de leite) com fita de cetim e flor',
        price: 'R$ 3.99',
    },
    {
        images: 'images/thumbnail_IMG-20230516-WA0008 (1).jpg',
        title: 'Tradicional',
        desc: 'Bem casado tradicional(doce de leite) com fita de cetim, flor e cúpula de vidro',
        price: 'R$ 29.00',
    },
    {
        images: 'images/IMG-20230516-WA0009.jpg',
        title: 'Tradicional',
        desc: 'Bem casado tradicional(doce de leite) com fita de cetim, flor e cúpula de vidro',
        price: 'R$ 29.00',
    },
    {
        images: 'images/bem1.jpg',
        title: 'Tradicional',
        desc: 'Bem casado tradicional(doce de leite), papel crepom e fita de cetim',
        price: 'R$ 2.99',
    },
    {
        images: 'images/IMG-20230515-WA0099.jpg',
        title: 'Tradicional',
        desc: 'Bem casado tradicional(doce de leite), papel crepom, fita de cetim e flor',
        price: 'R$ 3.99',
    },
    {
        images: 'images/IMG-20230515-WA0075.jpg',
        title: 'Tradicional',
        desc: 'Bem casado tradicional(doce de leite), papel crepom, fita de cetim e flor',
        price: 'R$ 2.99',
    },
    {
        images: 'images/IMG-20230515-WA0063.jpg',
        title: 'Tradicional',
        desc: 'Bem casado tradicional(doce de leite), papel crepom, fita de cetim e flor',
        price: 'R$ 2.99',
    },
    {
        images: 'images/bem_nascido1.jpg',
        title: 'Tradicional',
        desc: 'Bem casado tradicional(doce de leite), papel crepom e fita de voal decorada',
        price: 'R$ 3.99',
    },
    {
        images: 'images/bem_nascido2.jpg',
        title: 'Tradicional',
        desc: 'Bem casado tradicional(doce de leite), papel crepom e fita infantil',
        price: 'R$ 3.99',
    },
    {
        images: 'images/IMG-20230515-WA0090.jpg',
        title: 'Tradicional',
        desc: 'Bem casado tradicional(doce de leite), papel crepom e fita de cetim decorada',
        price: 'R$ 3.99',
    },
    {
        images: 'images/IMG-20230515-WA0071.jpg',
        title: 'Tradicional',
        desc: 'Bem casado tradicional(doce de leite), papel crepom, fita de cetim e ursinho',
        price: 'R$ 3.99',
    },
    {
        images: 'images/IMG-20230515-WA0070.jpg',
        title: 'Tradicional',
        desc: 'Bem casado tradicional(doce de leite), papel crepom, fita de cetim e ursinho',
        price: 'R$ 3.99',
    },
    {
        images: 'images/IMG-20230515-WA0081.jpg',
        title: 'Tradicional',
        desc: 'Bem casado tradicional(doce de leite), papel crepom personalizado e fita de cetim',
        price: 'R$ 3.99',
    },
    {
        images: 'images/IMG-20230515-WA0079.jpg',
        title: 'Tradicional',
        desc: 'Bem casado tradicional(doce de leite), papel crepom personalizado e fita de cetim',
        price: 'R$ 3.99',
    },
    {
        images: 'images/IMG-20230515-WA0080.jpg',
        title: 'Tradicional',
        desc: 'Bem casado tradicional(doce de leite), papel crepom personalizado e fita de cetim',
        price: 'R$ 3.99',
    },
    {
        images: 'images/bem2.jpg',
        title: 'Tradicional',
        desc: 'Bem casado tradicional(doce de leite), papel crepom e fita de cetim grossa',
        price: 'R$ 3.99',
    },
    {
        images: 'images/IMG-20230515-WA0078.jpg',
        title: 'Tradicional',
        desc: 'Bem casado tradicional(doce de leite), tecido e fita de cetim',
        price: 'R$ 3.99',
    },
    {
        images: 'images/IMG-20230515-WA0084.jpg',
        title: 'Tradicional',
        desc: 'Bem casado tradicional(doce de leite), tecido e renda',
        price: 'R$ 3.99',
    },
    {
        images: 'images/IMG-20230515-WA0087.jpg',
        title: 'Tradicional',
        desc: 'Bem casado tradicional(doce de leite), tecido e fita de cetim',
        price: 'R$ 3.99',
    },
    {
        images: 'images/IMG-20230515-WA0092.jpg',
        title: 'Tradicional',
        desc: 'Bem casado tradicional(doce de leite), tecido e fita cordão',
        price: 'R$ 3.99',
    },
    {
        images: 'images/IMG-20230515-WA0072.jpg',
        title: 'Tradicional',
        desc: 'Bem casado tradicional(doce de leite), papel crepom, fita de cetim e mine terço',
        price: 'R$4.50',
    },
];

export default products;